// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	models "github.com/FrancoLiberali/cql-tutorial/models"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
)

func (cityConditions cityConditions) Country(conditions ...condition.Condition[models.Country]) condition.JoinCondition[models.City] {
	return condition.NewJoinCondition[models.City, models.Country](conditions, "Country", "CountryID", cityConditions.preload(), "ID", Country.preload())
}

type cityConditions struct {
	ID         condition.Field[models.City, model.UIntID]
	Name       condition.StringField[models.City]
	Population condition.NumericField[models.City, int]
	CountryID  condition.UpdatableField[models.City, model.UIntID]
}

var City = cityConditions{
	CountryID:  condition.NewUpdatableField[models.City, model.UIntID]("CountryID", "", ""),
	ID:         condition.NewField[models.City, model.UIntID]("ID", "", ""),
	Name:       condition.NewStringField[models.City]("Name", "", ""),
	Population: condition.NewNumericField[models.City, int]("Population", "", ""),
}

// Preload allows preloading the City when doing a query
func (cityConditions cityConditions) preload() condition.Condition[models.City] {
	return condition.NewPreloadCondition[models.City](cityConditions.ID, cityConditions.Name, cityConditions.Population, cityConditions.CountryID)
}
