// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	models "github.com/FrancoLiberali/cql-tutorial/models"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
)

var cityScanner = &condition.Scanner[models.City]{
	AssignValues: func(dest *models.City, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = model.UIntID(v.Int64)
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "population":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner population: bad type %T", values[i])
				}
				if v.Valid {
					dest.Population = int(v.Int64)
				}
			case "country_id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner country_id: bad type %T", values[i])
				}
				dest.CountryID = model.UIntID(v.Int64)
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				condition.ReleaseNullInt64(values[i])
			case "name":
				condition.ReleaseNullString(values[i])
			case "population":
				condition.ReleaseNullInt64(values[i])
			case "country_id":
				condition.ReleaseNullInt64(values[i])
			default:
				condition.ReleaseNullSink(values[i])
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireNullInt64()
			case "name":
				values[i] = condition.AcquireNullString()
			case "population":
				values[i] = condition.AcquireNullInt64()
			case "country_id":
				values[i] = condition.AcquireNullInt64()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var cityCountryJoinScanner = &condition.RelationScanner[models.City, models.Country]{
	ChildScanner: countryScanner,
	Mount: func(p *models.City, c *models.Country) {
		p.Country = c
	},
	RelationField: "Country",
	SetNil: func(p *models.City) {
		p.Country = nil
	},
}

func init() {
	condition.RegisterScanner(cityScanner)
	City.ID = condition.NewField[models.City, model.UIntID]("ID", "", "", cityScanner)
	City.Name = condition.NewStringField[models.City]("Name", "", "", cityScanner)
	City.Population = condition.NewNumericField[models.City, int]("Population", "", "", cityScanner)
	City.CountryID = condition.NewUpdatableField[models.City, model.UIntID]("CountryID", "", "", cityScanner)
}
