// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package conditions

import (
	"database/sql"
	"fmt"
	models "github.com/FrancoLiberali/cql-tutorial/models"
	condition "github.com/FrancoLiberali/cql/condition"
	model "github.com/FrancoLiberali/cql/model"
	gorm "gorm.io/gorm"
)

var countryScanner = &condition.Scanner[models.Country]{
	AssignValues: func(dest *models.Country, columns []string, values []any) error {
		for i, c := range columns {
			switch c {
			case "id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner id: bad type %T", values[i])
				}
				dest.ID = model.UIntID(v.Int64)
			case "name":
				v, ok := values[i].(*sql.NullString)
				if !ok {
					return fmt.Errorf("cql scanner name: bad type %T", values[i])
				}
				if v.Valid {
					dest.Name = v.String
				}
			case "capital_id":
				v, ok := values[i].(*sql.NullInt64)
				if !ok {
					return fmt.Errorf("cql scanner capital_id: bad type %T", values[i])
				}
				dest.CapitalID = model.UIntID(v.Int64)
			}
		}
		return nil
	},
	ReleaseValues: func(columns []string, values []any) {
		for i, c := range columns {
			switch c {
			case "id":
				condition.ReleaseNullInt64(values[i])
			case "name":
				condition.ReleaseNullString(values[i])
			case "capital_id":
				condition.ReleaseNullInt64(values[i])
			default:
				condition.ReleaseNullSink(values[i])
			}
		}
	},
	ScanValues: func(columns []string) ([]any, error) {
		values := make([]any, len(columns))
		for i, c := range columns {
			switch c {
			case "id":
				values[i] = condition.AcquireNullInt64()
			case "name":
				values[i] = condition.AcquireNullString()
			case "capital_id":
				values[i] = condition.AcquireNullInt64()
			default:
				values[i] = condition.AcquireNullSink()
			}
		}
		return values, nil
	},
}
var countryCapitalJoinScanner = &condition.RelationScanner[models.Country, models.City]{
	ChildScanner: cityScanner,
	Mount: func(p *models.Country, c *models.City) {
		p.Capital = c
	},
	RelationField: "Capital",
	SetNil: func(p *models.Country) {
		p.Capital = nil
	},
}
var countryCitiesHasManyLoader = &condition.HasManyLoader[models.Country, models.City]{
	BuildQuery: func(tx *gorm.DB, parentIDs []any, nested []condition.Condition[models.City]) (*condition.Query[models.City], error) {
		typedIDs := make([]condition.ValueOfType[model.UIntID], len(parentIDs))
		for i, id := range parentIDs {
			typedIDs[i] = condition.UIntID(id.(model.UIntID))
		}
		conds := append([]condition.Condition[models.City]{City.CountryID.Is().In(typedIDs...)}, nested...)
		return condition.NewQuery[models.City](tx, conds...), nil
	},
	ChildFK: func(c *models.City) any {
		return c.CountryID
	},
	CollectionField: "Cities",
	Mount: func(p *models.Country, children []*models.City) {
		values := make([]models.City, len(children))
		for i, c := range children {
			values[i] = *c
		}
		p.Cities = &values
	},
	ParentID: func(p *models.Country) any {
		return p.ID
	},
}

func init() {
	condition.RegisterScanner(countryScanner)
	Country.ID = condition.NewField[models.Country, model.UIntID]("ID", "", "", countryScanner)
	Country.Name = condition.NewStringField[models.Country]("Name", "", "", countryScanner)
	Country.CapitalID = condition.NewUpdatableField[models.Country, model.UIntID]("CapitalID", "", "", countryScanner)
	Country.Cities = Country.Cities.WithParentScanner(countryScanner)
}
