// Code generated by cql-gen v0.0.5, DO NOT EDIT.
package models

import preload "github.com/FrancoLiberali/cql/preload"

func (m City) GetCountry() (*Country, error) {
	return preload.VerifyPointerLoaded[Country](m.CountryID, m.Country)
}
func (m Country) GetCapital() (*City, error) {
	return preload.VerifyPointerLoaded[City](m.CapitalID, m.Capital)
}
