// Code generated by cql-gen v0.1.0, DO NOT EDIT.
package models

import preload "github.com/FrancoLiberali/cql/preload"

func (m City) GetCountry() (*Country, error) {
	return preload.VerifyPointerWithIDLoaded[Country](m.CountryID, m.Country)
}
func (m Country) GetCapital() (*City, error) {
	return preload.VerifyPointerWithIDLoaded[City](m.CapitalID, m.Capital)
}
func (m Country) GetCities() ([]City, error) {
	return preload.VerifyCollectionLoaded[City](m.Cities)
}
